# Generated by Django 3.0.7 on 2020-08-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=60)),
                ('tel', models.IntegerField()),
                ('passport', models.CharField(max_length=50)),
                ('products', models.TextField()),
                ('summ', models.IntegerField()),
                ('date', models.DateField()),
                ('lifetime', models.DateField()),
            ],
        ),
    ]
