# Generated by Django 3.0.7 on 2020-08-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='summ',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='tel',
            field=models.CharField(max_length=13),
        ),
    ]
