# Generated by Django 3.0.7 on 2020-08-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200817_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='summ',
            field=models.CharField(max_length=90),
        ),
    ]
