# Generated by Django 3.0.7 on 2020-08-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200825_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='lifetime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='products',
            field=models.TextField(null=True),
        ),
    ]
