# Generated by Django 3.0.7 on 2020-08-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200825_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='passport',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
