# Generated by Django 3.0.7 on 2020-08-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200825_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='first',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='last',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='summ',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='tel',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
