# Generated by Django 3.0.7 on 2020-10-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200825_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='first',
        ),
        migrations.RemoveField(
            model_name='data',
            name='last',
        ),
        migrations.RemoveField(
            model_name='data',
            name='passport',
        ),
        migrations.AddField(
            model_name='data',
            name='full_name',
            field=models.CharField(default='malumot topilmadi', max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(default='malumot topilmadi'),
        ),
        migrations.AlterField(
            model_name='data',
            name='lifetime',
            field=models.DateField(default='malumot topilmadi'),
        ),
        migrations.AlterField(
            model_name='data',
            name='products',
            field=models.TextField(default='malumot topilmadi'),
        ),
        migrations.AlterField(
            model_name='data',
            name='summ',
            field=models.CharField(default='malumot topilmadi', max_length=90),
        ),
        migrations.AlterField(
            model_name='data',
            name='tel',
            field=models.CharField(default='malumot topilmadi', max_length=13),
        ),
    ]
