# Generated by Django 3.0.7 on 2020-10-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201017_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(default=0.0),
        ),
        migrations.AlterField(
            model_name='data',
            name='lifetime',
            field=models.DateField(default=0.0),
        ),
    ]
