# Generated by Django 3.0.7 on 2020-10-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201017_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='lifetime',
            field=models.DateField(null=True),
        ),
    ]
