# Generated by Django 3.0.7 on 2020-10-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201017_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='full_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
