# Generated by Django 3.0.7 on 2020-10-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201017_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
