# Generated by Django 3.0.7 on 2020-10-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20201017_1203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Info',
        ),
    ]
